language: go

go:
  - 1.6beta1

env:
  global:
    - BUILD_GOARCH=amd64
  matrix:
    - BUILD_GOOS=darwin
    - BUILD_GOOS=windows
    - BUILD_GOOS=linux

script:
  - go env
  - go get -t -v ./...
  - go test -v ./...
  - GOOS=$BUILD_GOOS GOARCH=$BUILD_GOARCH go env
  - GOOS=$BUILD_GOOS GOARCH=$BUILD_GOARCH make releases
