language: go

go:
  - 1.6beta1

env:
  global:
    - GOARCH=amd64
  matrix:
    - GOOS=darwin
    - GOOS=windows
    - GOOS=linux

after_success:
  - go build -v -o "./dist/todo-backend-$TRAVIS_BRANCH.$GOARCH" github.com/gabesullice/todo-backend
